### ISSUE TITLE
bug in 0.2.27

### ISSUE THREAD

**Issue by digitaladapt** [eco-stake/restake#113]
line 61 of /scripts/autostake.mjs:
`let grantedAddresses = await this.getGrantedAddresses(addresses)`
passes `addresses` as the only parameter, which doesn't match the function definition
on line 137 (same file):
`async getGrantedAddresses(client, addresses){`

Results in the following error:
```
file:///usr/src/app/scripts/autostake.mjs:138
    let grantCalls = addresses.map(item => {
                               ^

TypeError: Cannot read properties of undefined (reading 'map')
    at Autostake.getGrantedAddresses (file:///usr/src/app/scripts/autostake.mjs:138:32)
    at file:///usr/src/app/scripts/autostake.mjs:61:43
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async executeSync (file:///usr/src/app/src/utils/Helpers.mjs:44:5)
    at async Autostake.run (file:///usr/src/app/scripts/autostake.mjs:76:5)
```

I'll work on a pull request to fix this later, just wanted to make people aware in the meantime.

**Comment by tombeynon** [comment]
Eurgh thank you @digitaladapt, I'll fix this now

**Comment by tombeynon** [comment]
Thanks again for the report @digitaladapt, fixed in master
