### ISSUE TITLE
autostake.mjs fails with new release

### ISSUE THREAD

**Issue by BlockNgine** [eco-stake/restake#147]
since this commit https://github.com/eco-stake/restake/commit/237c3c1d644b7cd4d3b3740e7ef88421d841d437

```
file:///root/restake/scripts/autostake.mjs:113
    return client.queryClient.getBalance(client.operator.botAddress, client.network.denom)
                                                         ^

TypeError: Cannot read properties of undefined (reading 'botAddress')
    at Autostake.checkBalance (file:///root/restake/scripts/autostake.mjs:113:58)
    at file:///root/restake/scripts/autostake.mjs:47:20
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async executeSync (file:///root/restake/src/utils/Helpers.mjs:44:5)
    at async Autostake.run (file:///root/restake/scripts/autostake.mjs:75:5)
```

**Comment by tombeynon** [comment]
Fixed in master, thank you @BlockNgine and @pwnfoo
