### ISSUE TITLE
Error: This chain does not support amino conversion for Authz messages

### ISSUE THREAD

**Issue by activenodes** [eco-stake/restake#635]
These errors appeared after the update, but everything works fine
```
[07:49:26.717] [..] reward is too low, skipping
[07:49:26.722] [..] reward is too low, skipping
[07:49:26.722] Sending batch 1
Error: This chain does not support amino conversion for Authz messages
    at file:///usr/src/app/src/utils/SigningClient.mjs:242:15
    at Array.map (<anonymous>)
    at convertToAmino (file:///usr/src/app/src/utils/SigningClient.mjs:240:21)
    at sign (file:///usr/src/app/src/utils/SigningClient.mjs:186:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.signAndBroadcast (file:///usr/src/app/src/utils/SigningClient.mjs:133:20)
    at async NetworkRunner.sendMessages (file:///usr/src/app/src/autostake/NetworkRunner.mjs:291:16)
    at async file:///usr/src/app/src/autostake/NetworkRunner.mjs:243:9
    at async Promise.all (index 7)
    at async executeSync (file:///usr/src/app/src/utils/Helpers.mjs:124:5)
[07:49:33.219] Sent 74 messages - [..]
[07:49:33.221] Sent 1/1 transactions
[07:49:33.222] TX 1: Sent 74 messages -  [..]
[07:49:33.287] Autostake completed after 1 attempt(s)
[07:49:33.288] Attempt 1:
[07:49:33.288] Sent 1/1 transactions
[07:49:33.289] TX 1: Sent 74 messages - 0 [..]
[07:49:33.289] Autostake finished
```

**Comment by tombeynon** [comment]
Ahh yes.. that will be noisy lol. It's just a log so you can ignore, but I'll sort that out today.
